<?php

namespace AppBundle\Repository;

/**
 * CajaCierreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaCierreRepository extends \Doctrine\ORM\EntityRepository
{
}
