<?php

namespace AppBundle\Repository;

/**
 * CajaAperturaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaAperturaRepository extends \Doctrine\ORM\EntityRepository
{
}
