<?php

namespace AppBundle\Repository;

/**
 * CajaAperturaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaAperturaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
