<?php

namespace AppBundle\Repository;

/**
 * CajaCuentaBancoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CajaCuentaBancoRepository extends \Doctrine\ORM\EntityRepository
{
}
