<?php

namespace AppBundle\Repository;

/**
 * CompraAnuladaNotaCreditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompraAnuladaNotaCreditoRepository extends \Doctrine\ORM\EntityRepository
{
}
