<?php

namespace AppBundle\Repository;

/**
 * CompraFormaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompraFormaPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
