<?php

namespace AppBundle\Repository;

/**
 * ComponenteXDocumentoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComponenteXDocumentoRepository extends \Doctrine\ORM\EntityRepository
{
}
