<?php

namespace AppBundle\Repository;

/**
 * CuentaTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
