<?php

namespace AppBundle\Repository;

/**
 * CuentaBancoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaBancoRepository extends \Doctrine\ORM\EntityRepository
{
}
