<?php

namespace AppBundle\Repository;

/**
 * DetalleCompraAnuladaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleCompraAnuladaRepository extends \Doctrine\ORM\EntityRepository
{
}
