<?php

namespace AppBundle\Repository;

/**
 * DetalleCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleCompraRepository extends \Doctrine\ORM\EntityRepository
{
}
