<?php

namespace AppBundle\Repository;

/**
 * DetalleProformaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProformaRepository extends \Doctrine\ORM\EntityRepository
{
}
