<?php

namespace AppBundle\Repository;

/**
 * DetalleProformaEntregaDatosEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProformaEntregaDatosEnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
