<?php

namespace AppBundle\Repository;

/**
 * DetalleVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
