<?php

namespace AppBundle\Repository;

/**
 * DetalleVentaEntregaDatosEnvioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleVentaEntregaDatosEnvioRepository extends \Doctrine\ORM\EntityRepository
{
}
