<?php

namespace AppBundle\Repository;

/**
 * DetalleProformaEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleProformaEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
