<?php

namespace AppBundle\Repository;

/**
 * DetalleVentaEntregaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetalleVentaEntregaRepository extends \Doctrine\ORM\EntityRepository
{
}
