<?php

namespace AppBundle\Repository;

/**
 * EmpresaLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
