<?php

namespace AppBundle\Repository;

/**
 * FacturaVentaTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaVentaTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
