<?php

namespace AppBundle\Repository;

/**
 * FacturaVentaNubefactErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaVentaNubefactErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
