<?php

namespace AppBundle\Repository;

/**
 * FacturaCompraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaCompraRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 *
	 * @return array
	 */
	public function findLastId()
	{

			$qb = $this->createQueryBuilder('fc');
			$qb->setMaxResults(1);
			$qb->orderBy('fc.id', 'DESC');

			return $qb->getQuery()->getOneOrNullResult();		
	}	
}
