<?php

namespace AppBundle\Repository;

/**
 * FacturaVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacturaVentaRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 *
	 * @return array
	 */
	public function findLastId()
	{

	    // $qb = $this->_em->createQueryBuilder();
	    // $qb->select('f')
	    //     ->from('AppBundle:MercadoLocal', 'm')
	    //     ->join('m.usuarios', 'u')
	    //     ->where('u.usuario =:usuario')
	    //     ->orderBy('m.orden')
	    //     ->setParameter('usuario', $usuario->getId());

	    // return $qb->getQuery()->getResult();


			$qb = $this->createQueryBuilder('fv');
			$qb->setMaxResults(1);
			$qb->orderBy('fv.id', 'DESC');

			return $qb->getQuery()->getOneOrNullResult();		
	}


}
