<?php

namespace AppBundle\Repository;

/**
 * GuiaRemisionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GuiaRemisionRepository extends \Doctrine\ORM\EntityRepository
{
}
