<?php

namespace AppBundle\Repository;

/**
 * LogModificacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogModificacionRepository extends \Doctrine\ORM\EntityRepository
{
}
