<?php

namespace AppBundle\Repository;

/**
 * ModificacionTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModificacionTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
