<?php

namespace AppBundle\Repository;

/**
 * MotivoTrasladoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotivoTrasladoRepository extends \Doctrine\ORM\EntityRepository
{
}
