<?php

namespace AppBundle\Repository;

/**
 * NotaDebitoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaDebitoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
