<?php

namespace AppBundle\Repository;

/**
 * NotaCreditoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaCreditoRepository extends \Doctrine\ORM\EntityRepository
{
}
