<?php

namespace AppBundle\Repository;

/**
 * NotaDebitoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaDebitoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
