<?php

namespace AppBundle\Repository;

/**
 * NotaCreditoDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaCreditoDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
