<?php

namespace AppBundle\Repository;

/**
 * NotaDebitoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaDebitoRepository extends \Doctrine\ORM\EntityRepository
{
}
