<?php

namespace AppBundle\Repository;

/**
 * NotaCreditoTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotaCreditoTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
