<?php

namespace AppBundle\Repository;

/**
 * NubefactErrorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NubefactErrorRepository extends \Doctrine\ORM\EntityRepository
{
}
