<?php

namespace AppBundle\Repository;

/**
 * PedidoVentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoVentaRepository extends \Doctrine\ORM\EntityRepository
{
}
