<?php

namespace AppBundle\Repository;

/**
 * PedidoVentaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PedidoVentaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
