<?php

namespace AppBundle\Repository;

/**
 * ProductoMarcaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoMarcaRepository extends \Doctrine\ORM\EntityRepository
{
}
