<?php

namespace AppBundle\Repository;

/**
 * ProductoUnidadRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoUnidadRepository extends \Doctrine\ORM\EntityRepository
{
}
