<?php

namespace AppBundle\Repository;

/**
 * ProductoBaseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoBaseRepository extends \Doctrine\ORM\EntityRepository
{
}
