<?php

namespace AppBundle\Repository;

/**
 * ProductoCodigoSunatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoCodigoSunatRepository extends \Doctrine\ORM\EntityRepository
{
}
