<?php

namespace AppBundle\Repository;

/**
 * ProductoXLocalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductoXLocalRepository extends \Doctrine\ORM\EntityRepository
{
}
