<?php

namespace AppBundle\Repository;

/**
 * ProformaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProformaRepository extends \Doctrine\ORM\EntityRepository
{
}
