<?php

namespace AppBundle\Repository;

/**
 * ProveedorServicioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorServicioRepository extends \Doctrine\ORM\EntityRepository
{
}
