<?php

namespace AppBundle\Repository;

/**
 * ProveedorTipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProveedorTipoRepository extends \Doctrine\ORM\EntityRepository
{
}
