<?php

namespace AppBundle\Repository;

/**
 * SunatT5Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SunatT5Repository extends \Doctrine\ORM\EntityRepository
{
}
