<?php

namespace AppBundle\Repository;

/**
 * SunatT4Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SunatT4Repository extends \Doctrine\ORM\EntityRepository
{
}
