<?php

namespace AppBundle\Repository;

/**
 * SunatT7Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SunatT7Repository extends \Doctrine\ORM\EntityRepository
{
}
