<?php

namespace AppBundle\Repository;

/**
 * SunatF121Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SunatF121Repository extends \Doctrine\ORM\EntityRepository
{
}
