<?php

namespace AppBundle\Repository;

/**
 * TipoCambioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoCambioRepository extends \Doctrine\ORM\EntityRepository
{
}
