<?php

namespace AppBundle\Repository;

/**
 * TipoImpuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoImpuestoRepository extends \Doctrine\ORM\EntityRepository
{
}
