<?php

namespace AppBundle\Repository;

/**
 * TransferenciaDineroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenciaDineroRepository extends \Doctrine\ORM\EntityRepository
{
}
