<?php

namespace AppBundle\Repository;

/**
 * TransaccionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionRepository extends \Doctrine\ORM\EntityRepository
{
}
