<?php

namespace AppBundle\Repository;

/**
 * TransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
