<?php

namespace AppBundle\Repository;

/**
 * TransaccionDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransaccionDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
