<?php

namespace AppBundle\Repository;

/**
 * TransferenciaXProductoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenciaXProductoRepository extends \Doctrine\ORM\EntityRepository
{
}
