<?php

namespace AppBundle\Repository;

/**
 * TransferenciaXTransporteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransferenciaXTransporteRepository extends \Doctrine\ORM\EntityRepository
{
}
