<?php

namespace AppBundle\Repository;

/**
 * VentaFormaPagoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VentaFormaPagoRepository extends \Doctrine\ORM\EntityRepository
{
}
