app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /main

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
    path:  /
    defaults:  { _controller: FOSUserBundle:Security:login, _method: POST }

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_register:
    path:  /register
    defaults: { _controller: FOSUserBundle:Registration:register }

imprimir_ticket:
    path:  /imprimir/ticket
    defaults:  { _controller: AppBundle:Default:imprimirTicket, _method: GET }

obtenerdatosempresa:
    path:  /obtenerdatosempresa
    defaults:  { _controller: AppBundle:ServicioAjax:obtenerDatosEmpresa, _method: GET }

consultar_estado_boleta:
    path:  /consultar/estado/boleta
    defaults:  { _controller: AppBundle:ServicioAjax:consultarEstadoBoleta, _method: GET } 

establecer_tipo_de_cambio:
    path:  /establecer/tipo/cambio
    defaults:  { _controller: AppBundle:Default:establecerTipoDeCambio, _method: GET }

set_email_registro:
    path:  /set/email/registro
    defaults:  { _controller: FOSUserBundle:Security:setEmailRegistro, _method: GET }

usuario_registro:
    path:  /usuario/registro
    defaults:  { _controller: FOSUserBundle:Security:usuarioRegistro, _method: [GET,POST] }